# Generated from create-LCDmix.Rmd: do not edit by hand

#' Summarize LCDmix cross-validation runs and choose optimal penalties
#'
#' Reads per-run CV results saved by \code{\link{cv_lcd}} from
#' \code{save_dir}, aggregates them into a long CV table, computes a reduced
#' summary by (\code{alpha_idx}, \code{theta_idx}), and selects the optimal
#' (\code{lambda_alpha}, \code{lambda_theta}) by maximizing the mean
#' trimmed held-out (penalized) log-likelihood across folds.
#'
#' @param index_matrix Numeric matrix generated by \code{\link{cv_idx_mat}}
#'   with columns \code{alpha_idx}, \code{theta_idx}, \code{seed_idx},
#'   \code{fold_idx}, \code{lambda_alpha}, \code{lambda_theta}.
#' @param save_dir Character; directory where per-run files
#'   \code{"<alpha_idx>-<theta_idx>-<seed_idx>-<fold_idx>.rds"} (or simulation
#'   variant with \code{sim_idx} prefix) are stored. Default \code{"./result"}.
#' @param simul Logical; if \code{TRUE}, look for filenames that include
#'   \code{sim_idx} as a leading component. Default \code{FALSE}.
#' @param sim_idx Integer; simulation index used only when \code{simul = TRUE}.
#'
#' @details
#' Each per-run RDS file is expected to contain (at least) the elements:
#' \code{L} (training objective), \code{prop_inf} (proportion of non-finite
#' per-row log-likelihoods on the hold-out), and \code{trimmed_loglik}
#' (trimmed penalized held-out log-likelihood). Missing files are skipped with
#' a warning. Within each (\code{alpha_idx}, \code{theta_idx}, \code{fold_idx})
#' group, the row with the largest \code{L} is kept (breaking ties by order).
#' The CV score for a penalty pair is the mean of \code{trimmed_loglik} across
#' folds (with \code{na.rm = TRUE}). For selecting optimal penalties, \code{NA}
#' CV scores are treated as \code{-Inf} to ensure a deterministic choice.
#'
#' @return A list with:
#' \describe{
#'   \item{\code{CVmat}}{Data frame: the full long-form table with one row per run,
#'     including \code{L}, \code{prop_inf}, and \code{trimmed_loglik}.}
#'   \item{\code{reduced_mat}}{Numeric matrix: one row per (\code{alpha_idx}, \code{theta_idx}),
#'     including \code{lambda_alpha}, \code{lambda_theta}, the mean CV score
#'     (\code{cv_score}), and counts of non-\code{NA} \code{L} (\code{counts}).}
#'   \item{\code{opt_lambdas}}{Numeric length-2 vector:
#'     \code{c(lambda_alpha, lambda_theta)} for the maximizing pair.}
#'   \item{\code{max_prop_inf}}{Maximum \code{prop_inf} observed over all runs (useful for diagnostics).}
#' }
#'
#' @seealso \code{\link{cv_lcd}}, \code{\link{eval_lcd}},
#'   \code{\link{cv_idx_mat}}
#'
#' @examples
#' \dontrun{
#' # After running cv_lcd(...):
#' load(file.path("cv_runs", "index_matrix.Rdata"))  # loads index_matrix
#' summ <- cv_lcd_summary(index_matrix, save_dir = "cv_runs")
#' summ$opt_lambdas
#' }
#'
#' @export
cv_lcd_summary <- function(
  index_matrix,
  save_dir = "./cv_saves",
  cv_by_trimmed = T,
  equal_w = T
) {
  n_runs <- nrow(index_matrix)
  # Initialize CV matrix with placeholders
  CVmat <- cbind(
    index_matrix        = index_matrix,
    fit_trimmed_loglik  = rep(NA_real_, n_runs),
    fit_med_loglik      = rep(NA_real_, n_runs),
    fit_loglik          = rep(NA_real_, n_runs),
    eval_prop_inf       = rep(NA_real_, n_runs),
    eval_trimmed_loglik = rep(NA_real_, n_runs),
    eval_med_loglik     = rep(NA_real_, n_runs),
    eval_penalty        = rep(NA_real_, n_runs),
    eval_w              = rep(NA_real_, n_runs),
    eval_trimmed_w      = rep(NA_real_, n_runs)
  )
  CVmat <- as.data.frame(CVmat)
  
  # Load each run's results
  for (i in seq_len(n_runs)) {
    alpha_idx  <- index_matrix[i, "alpha_idx"]
    theta_idx  <- index_matrix[i, "theta_idx"]
    seed_idx   <- index_matrix[i, "seed_idx"]
    fold_idx   <- index_matrix[i, "fold_idx"]
    
    file_name  <- file.path(
    save_dir,
    sprintf("%d-%d-%d-%d.rds",
            alpha_idx, theta_idx, seed_idx, fold_idx))
    
    # skip runs whose file never got written
    if (!file.exists(file_name)) {
      warning("CV file missing: ", file_name, "; leaving NA")
      next
    }
    # load
    mat = readRDS(file_name)
    CVmat[i, "fit_trimmed_loglik"]  <- mat$fit_trimmed_loglik
    CVmat[i, "fit_med_loglik"]      <- mat$fit_med_loglik
    CVmat[i, "fit_loglik"]          <- mat$fit_loglik
    CVmat[i, "eval_prop_inf"]       <- mat$eval_prop_inf 
    CVmat[i, "eval_trimmed_loglik"] <- mat$eval_trimmed_loglik
    CVmat[i, "eval_med_loglik"]     <- mat$eval_med_loglik
    CVmat[i, "eval_penalty"]        <- mat$eval_penalty
    CVmat[i, "eval_w"]              <- mat$eval_w
    CVmat[i, "eval_trimmed_w"]      <- mat$eval_trimmed_w
  }
  ## 4) For each (alpha_idx, theta_idx, fold_idx), keep the row with largest fit_loglik
  gid <- interaction(CVmat$alpha_idx, CVmat$theta_idx, CVmat$fold_idx, drop = TRUE)
  row_groups <- split(seq_len(nrow(CVmat)), gid)
  
  if (cv_by_trimmed) {
    pick <- CVmat$fit_trimmed_loglik
  } else {
    pick <- CVmat$fit_med_loglik
  }

  pick_idx <- vapply(row_groups, function(idx) {
    v <- pick[idx]
    if (all(!is.finite(v))) return(NA_integer_)  # no usable value in this group
    idx[which.max(v)]                 # pick the row index with max loglik
  }, integer(1L))
  
  selected <- CVmat[pick_idx[!is.na(pick_idx)], , drop = FALSE]
  
  # Group selected rows by (alpha_idx, theta_idx)
  gid2 <- interaction(selected$alpha_idx, selected$theta_idx, drop = TRUE)
  row_groups2 <- split(seq_len(nrow(selected)), gid2)

  ## 5) Average those per-fold maxima across folds → cv_score per (alpha,theta)
  cv_score <- vapply(row_groups2, function(idx) {
    if (equal_w) {
      if (cv_by_trimmed) {
        mean(selected$eval_trimmed_loglik[idx], na.rm = TRUE)
      } else {
        mean(selected$eval_med_loglik[idx], na.rm = TRUE)
      }
    } else {
      if (cv_by_trimmed) {
        weighted.mean(selected$eval_trimmed_loglik[idx], selected$eval_trimmed_w[idx], na.rm = TRUE)
      } else {
        weighted.mean(selected$eval_med_loglik[idx], selected$eval_w[idx], na.rm = TRUE)
      }
    }
  }, double(1L))
  
  mat <- cbind(
    do.call(rbind, lapply(strsplit(names(row_groups2), "[.]"), as.numeric)),
    cv_score
  )
  colnames(mat)[1:2] <- c("alpha_idx", "theta_idx")
  
  ## 6) Unique lambda values per combo (from the original matrix)
  unique_lams <- unique(CVmat[, c("alpha_idx","theta_idx","lambda_alpha","lambda_theta")])

  ## 7) Count rows in CVmat with non-NA and finite loglik per (alpha_idx, theta_idx)
  if (cv_by_trimmed) {
    counts_df <- aggregate(
      I(is.finite(eval_trimmed_loglik) & is.finite(fit_trimmed_loglik)) ~ alpha_idx + theta_idx,
      data = CVmat, FUN  = sum)
  } else {
    counts_df <- aggregate(
      I(is.finite(eval_med_loglik) & is.finite(fit_med_loglik)) ~ alpha_idx + theta_idx,
      data = CVmat, FUN  = sum)
  }
  names(counts_df)[3] <- "counts"
  
  ## 8) cbind
  reduced_mat <- merge(unique_lams, mat, by = c("alpha_idx","theta_idx"), all.x = TRUE)
  reduced_mat <- merge(reduced_mat, counts_df, by = c("alpha_idx","theta_idx"), all.x = TRUE)
  
  ## 9) Pick optimal lambdas
  score_vec <- reduced_mat$cv_score
  score_vec[!is.finite(score_vec)] <- -Inf   # handles NA and NaN
  opt_lambdas <- as.numeric(reduced_mat[which.max(score_vec), c("lambda_alpha", "lambda_theta")])

  return(list(
    CVmat        = CVmat,
    reduced_mat  = as.matrix(reduced_mat),
    opt_lambdas  = opt_lambdas,
    max_prop_inf = max(CVmat[, "eval_prop_inf"], na.rm = TRUE),
    cv_by_trimmed = cv_by_trimmed
  ))
}
