# Generated from create-LCDmix.Rmd: do not edit by hand

#' Summarize LCDmix cross-validation runs and choose optimal penalties
#'
#' Reads per-run CV results saved by \code{\link{cv_lcd}} from
#' \code{save_dir}, aggregates them into a long CV table, computes a reduced
#' summary by (\code{alpha_idx}, \code{theta_idx}), and selects the optimal
#' (\code{lambda_alpha}, \code{lambda_theta}) by maximizing the mean
#' trimmed held-out (penalized) log-likelihood across folds.
#'
#' @param index_matrix Numeric matrix generated by \code{\link{cv_idx_mat}}
#'   with columns \code{alpha_idx}, \code{theta_idx}, \code{seed_idx},
#'   \code{fold_idx}, \code{lambda_alpha}, \code{lambda_theta}.
#' @param save_dir Character; directory where per-run files
#'   \code{"<alpha_idx>-<theta_idx>-<seed_idx>-<fold_idx>.rds"} (or simulation
#'   variant with \code{sim_idx} prefix) are stored. Default \code{"./result"}.
#' @param simul Logical; if \code{TRUE}, look for filenames that include
#'   \code{sim_idx} as a leading component. Default \code{FALSE}.
#' @param sim_idx Integer; simulation index used only when \code{simul = TRUE}.
#'
#' @details
#' Each per-run RDS file is expected to contain (at least) the elements:
#' \code{L} (training objective), \code{prop_inf} (proportion of non-finite
#' per-row log-likelihoods on the hold-out), and \code{trimmed_loglik}
#' (trimmed penalized held-out log-likelihood). Missing files are skipped with
#' a warning. Within each (\code{alpha_idx}, \code{theta_idx}, \code{fold_idx})
#' group, the row with the largest \code{L} is kept (breaking ties by order).
#' The CV score for a penalty pair is the mean of \code{trimmed_loglik} across
#' folds (with \code{na.rm = TRUE}). For selecting optimal penalties, \code{NA}
#' CV scores are treated as \code{-Inf} to ensure a deterministic choice.
#'
#' @return A list with:
#' \describe{
#'   \item{\code{CVmat}}{Data frame: the full long-form table with one row per run,
#'     including \code{L}, \code{prop_inf}, and \code{trimmed_loglik}.}
#'   \item{\code{reduced_mat}}{Numeric matrix: one row per (\code{alpha_idx}, \code{theta_idx}),
#'     including \code{lambda_alpha}, \code{lambda_theta}, the mean CV score
#'     (\code{cv_score}), and counts of non-\code{NA} \code{L} (\code{counts}).}
#'   \item{\code{opt_lambdas}}{Numeric length-2 vector:
#'     \code{c(lambda_alpha, lambda_theta)} for the maximizing pair.}
#'   \item{\code{max_inf_prop}}{Maximum \code{prop_inf} observed over all runs (useful for diagnostics).}
#' }
#'
#' @seealso \code{\link{cv_lcd}}, \code{\link{eval_lcd}},
#'   \code{\link{cv_idx_mat}}
#'
#' @examples
#' \dontrun{
#' # After running cv_lcd(...):
#' load(file.path("cv_runs", "index_matrix.Rdata"))  # loads index_matrix
#' summ <- cv_lcd_summary(index_matrix, save_dir = "cv_runs")
#' summ$opt_lambdas
#' }
#'
#' @export
cv_lcd_summary <- function(
  index_matrix,
  save_dir = "./cv_saves"
) {
  n_runs <- nrow(index_matrix)
  # Initialize CV matrix with placeholders
  CVmat <- cbind(
    index_matrix,
    L              = rep(NA_real_, n_runs),
    prop_inf       = rep(NA_real_, n_runs),
    trimmed_loglik = rep(NA_real_, n_runs),
    finite_loglik  = rep(NA_real_, n_runs),
    theta_spars    = rep(NA_real_, n_runs),
    alpha_spars    = rep(NA_real_, n_runs)
  )
  CVmat <- as.data.frame(CVmat)
  
  # Load each run's results
  for (i in seq_len(n_runs)) {
    alpha_idx  <- index_matrix[i, "alpha_idx"]
    theta_idx  <- index_matrix[i, "theta_idx"]
    seed_idx   <- index_matrix[i, "seed_idx"]
    fold_idx   <- index_matrix[i, "fold_idx"]
    
    file_name  <- file.path(
    save_dir,
    sprintf("%d-%d-%d-%d.rds",
            alpha_idx, theta_idx, seed_idx, fold_idx))
    
    # skip runs whose file never got written
    if (!file.exists(file_name)) {
      warning("CV file missing: ", file_name, "; leaving NA")
      next
    }
    # load
    mat = readRDS(file_name)
    CVmat[i, "L"]              <- mat$L
    CVmat[i, "prop_inf"]       <- mat$prop_inf
    CVmat[i, "trimmed_loglik"] <- mat$trimmed_loglik
    CVmat[i, "finite_loglik"]  <- mat$finite_loglik
    CVmat[i, "theta_spars"]    <- mat$theta_spars
    CVmat[i, "alpha_spars"]    <- mat$alpha_spars
  }
  
  ## 4) For each (alpha_idx, theta_idx, fold_idx), keep the row with largest L
  # Order so that within each (alpha,theta,fold) the first row has max L (NAs go last)
  ord <- with(CVmat,
    order(alpha_idx, theta_idx, fold_idx, -L, na.last = TRUE)  # NAs go last
  )
  selected <- CVmat[ord, ]
  selected <- selected[!duplicated(selected[c("alpha_idx","theta_idx","fold_idx")]), ]
  
  ## Warn if any selected rows have NA trimmed_loglik
  if (any(is.na(selected$trimmed_loglik))) {
    warning("Selected rows contain NA trimmed_loglik values; they will be ignored when averaging.")
  }
  
  ## 5) Average the selected trimmed_loglik across folds -> cv_score per (alpha,theta)
  best_by_combo <- aggregate(
    trimmed_loglik~ alpha_idx + theta_idx,
    data = selected,
    FUN  = function(x) mean(x, na.rm = TRUE)
  )
  names(best_by_combo)[3] <- "cv_score"
  
  ## 6) Unique lambda values per combo (from the original matrix)
  unique_lams <- unique(CVmat[, c("alpha_idx","theta_idx","lambda_alpha","lambda_theta")])

  ## 7) Count rows in CVmat with non-NA L per (alpha_idx, theta_idx)
  counts_df <- aggregate(
    I(!is.na(L)) ~ alpha_idx + theta_idx,
    data = CVmat,
    FUN  = sum
  )
  names(counts_df)[3] <- "counts"
  
  ## 8) Merge & sort  (unchanged except for the new column name)
  reduced_mat <- merge(unique_lams, best_by_combo, by = c("alpha_idx","theta_idx"), all.x = TRUE)
  reduced_mat <- merge(reduced_mat, counts_df, by = c("alpha_idx","theta_idx"), all.x = TRUE)
  reduced_mat <- reduced_mat[order(reduced_mat$alpha_idx, reduced_mat$theta_idx), ]

  ## 9) Pick optimal lambdas
  score_vec <- reduced_mat$cv_score
  score_vec[!is.finite(score_vec)] <- -Inf   # handles NA and NaN
  opt_row <- which.max(score_vec)
  opt_lambdas <- as.numeric(reduced_mat[opt_row, c("lambda_alpha", "lambda_theta")])

  return(list(
    CVmat        = CVmat,
    reduced_mat  = as.matrix(reduced_mat),
    opt_lambdas  = opt_lambdas,
    max_inf_prop  = max(CVmat[, "prop_inf"], na.rm = TRUE)
  ))
}
